import JSZip from 'jszip'
import type { CertFile } from '../types'

/**
 * 인증서 파일들을 ZIP으로 압축
 */
export async function createCertZip(files: CertFile[]): Promise<Blob> {
  const zip = new JSZip()

  // kubernetes 폴더 구조 생성
  const kubernetesFolder = zip.folder('kubernetes')
  if (!kubernetesFolder) {
    throw new Error('Failed to create kubernetes folder')
  }

  files.forEach((file) => {
    kubernetesFolder.file(file.path, file.content)
  })

  // kubeconfig 파일이 있는지 확인
  const hasKubeconfig = files.some((f) => f.type === 'kubeconfig')

  // README 추가
  const readme = hasKubeconfig ? generateFullReadme(files) : generatePKIReadme(files)
  kubernetesFolder.file('README.md', readme)

  // 설치 스크립트 추가
  const installScript = hasKubeconfig ? generateFullInstallScript() : generatePKIInstallScript()
  kubernetesFolder.file('install.sh', installScript)

  return await zip.generateAsync({ type: 'blob' })
}

/**
 * PKI 전용 README.md 생성
 */
function generatePKIReadme(files: CertFile[]): string {
  const certFiles = files.filter((f) => f.type === 'certificate')
  const keyFiles = files.filter((f) => f.type === 'key')

  return `# Kubernetes SSL Certificates

Generated by web-kube-cert

## File Structure

\`\`\`
ssl/
├── ca.crt / ca.key                     # Kubernetes CA
├── apiserver.crt / apiserver.key       # API Server
├── apiserver-kubelet-client.crt / .key # Kubelet Client
├── apiserver-etcd-client.crt / .key    # etcd Client  
├── front-proxy-ca.crt / .key           # Front Proxy CA
├── front-proxy-client.crt / .key       # Front Proxy Client
├── sa.pub / sa.key                     # Service Account
└── etcd/
    ├── ca.crt / ca.key                 # etcd CA
    ├── server.crt / server.key         # etcd Server
    ├── peer.crt / peer.key             # etcd Peer
    └── healthcheck-client.crt / .key   # etcd Healthcheck
\`\`\`

## Summary

- Certificates: ${certFiles.length}
- Keys: ${keyFiles.length}
- Total: ${files.length} files

## Installation

\`\`\`bash
# Copy to server
sudo mkdir -p /etc/kubernetes/pki/etcd
sudo cp -r ssl/* /etc/kubernetes/pki/

# Set permissions
sudo chmod 600 /etc/kubernetes/pki/*.key
sudo chmod 600 /etc/kubernetes/pki/etcd/*.key
sudo chmod 644 /etc/kubernetes/pki/*.crt
sudo chmod 644 /etc/kubernetes/pki/etcd/*.crt

# Initialize cluster (skip cert phase)
sudo kubeadm init --skip-phases=certs
\`\`\`

Or use the install script:

\`\`\`bash
chmod +x install.sh
sudo ./install.sh
\`\`\`

## Security Notice

- Keep private keys (.key) secure
- Never commit to public repositories
`
}

/**
 * PKI 전용 설치 스크립트
 */
function generatePKIInstallScript(): string {
  return `#!/bin/bash
# Kubernetes SSL Installation Script

set -e

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
KUBE_PATH="/etc/kubernetes"

echo "Installing Kubernetes SSL certificates..."

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo ./install.sh)"
  exit 1
fi

# Backup existing certificates
if [ -d "$KUBE_PATH/pki" ]; then
  BACKUP_PATH="$KUBE_PATH/pki.backup.$(date +%Y%m%d%H%M%S)"
  echo "Backing up existing PKI to $BACKUP_PATH"
  cp -r "$KUBE_PATH/pki" "$BACKUP_PATH"
fi

# Create directories
mkdir -p "$KUBE_PATH/pki/etcd"

# Copy SSL files to pki directory
echo "Copying SSL files..."
cp -r "$SCRIPT_DIR/ssl/"* "$KUBE_PATH/pki/"

# Set permissions
echo "Setting permissions..."
chmod 600 "$KUBE_PATH/pki/"*.key 2>/dev/null || true
chmod 600 "$KUBE_PATH/pki/etcd/"*.key 2>/dev/null || true
chmod 644 "$KUBE_PATH/pki/"*.crt 2>/dev/null || true
chmod 644 "$KUBE_PATH/pki/"*.pub 2>/dev/null || true
chmod 644 "$KUBE_PATH/pki/etcd/"*.crt 2>/dev/null || true

echo ""
echo "Installation complete!"
echo ""
echo "Next steps:"
echo "  kubeadm init --skip-phases=certs"
`
}

/**
 * 전체 파일용 README.md 생성
 */
function generateFullReadme(files: CertFile[]): string {
  const certFiles = files.filter((f) => f.type === 'certificate')
  const keyFiles = files.filter((f) => f.type === 'key')
  const kubeconfigFiles = files.filter((f) => f.type === 'kubeconfig')

  return `# Kubernetes PKI Certificates

Generated by web-kube-cert

## Summary

- Certificates: ${certFiles.length}
- Keys: ${keyFiles.length}
- Kubeconfigs: ${kubeconfigFiles.length}
- Total: ${files.length} files

## Installation

\`\`\`bash
chmod +x install.sh
sudo ./install.sh
\`\`\`

## Security Notice

- Keep private keys (.key) secure
- Never commit to public repositories
`
}

/**
 * 전체 파일용 설치 스크립트
 */
function generateFullInstallScript(): string {
  return `#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
KUBE_PATH="/etc/kubernetes"

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

mkdir -p "$KUBE_PATH/pki/etcd"

if [ -d "$SCRIPT_DIR/pki" ]; then
  cp -r "$SCRIPT_DIR/pki/"* "$KUBE_PATH/pki/"
fi

for conf in admin.conf controller-manager.conf scheduler.conf kubelet.conf super-admin.conf; do
  if [ -f "$SCRIPT_DIR/$conf" ]; then
    cp "$SCRIPT_DIR/$conf" "$KUBE_PATH/"
  fi
done

chmod 600 "$KUBE_PATH/pki/"*.key 2>/dev/null || true
chmod 600 "$KUBE_PATH/pki/etcd/"*.key 2>/dev/null || true
chmod 600 "$KUBE_PATH/"*.conf 2>/dev/null || true

echo "Installation complete!"
`
}
